---
- name: test vars
  hosts: localhost
  gather_facts: no

  tasks:
  - debug:
      msg: "This is the second playbook in Workflow 2"

  - debug:
      msg: "Outputing Variable from Workflow 1 - Playbook 1 which is: {{ created_fact }}"